version: "3.9"

services:
  music_backend:
    build: .
    container_name: music_backend
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
    - .env
music_backend